# theme: jekyll-theme-hacker
show_downloads: false
#avatar: "gtr.png"
author: "dorian9007"
plugins: 
  - jekyll-seo-tag
# jekyll-theme-hacker
# jekyll-theme-slate
theme: jekyll-theme-cayman
github:
  is_project_page: true
